### ISSUE TITLE
lief enums seem to be incorrectly capitalised

### ISSUE THREAD

**Issue by addisoncrump** [quarkslab/pastis#17]
https://github.com/quarkslab/pastis/blob/917e0766bb090ab1a6b68a314c8573698c5a3060/libpastis/package.py#L266-L267

I don't think I'm holding this wrong; this causes the following error in a local fuzzbench run:

```
[fuzz] Running command: pastis-benchmark run -b /out/targets -w /out/corpus -s /out/seeds -m FULL -i ARGV -p 5551 --triton --hfuzz --hfuzz-threads 1 --aflpp --skip-cpufreq
Traceback (most recent call last):
  File "/usr/local/bin/pastis-benchmark", line 393, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/bin/pastis-benchmark", line 176, in run
    broker = PastisBroker(workspace,
  File "/usr/local/lib/python3.10/site-packages/pastisbroker/broker.py", line 88, in __init__
    self._find_binaries(binaries_dir)
  File "/usr/local/lib/python3.10/site-packages/pastisbroker/broker.py", line 710, in _find_binaries
    pkg = BinaryPackage.auto_directory(file)  # try creating a package
  File "/usr/local/lib/python3.10/site-packages/libpastis/package.py", line 219, in auto_directory
    p = BinaryPackage.auto(bin_f)
  File "/usr/local/lib/python3.10/site-packages/libpastis/package.py", line 172, in auto
    data = BinaryPackage._read_binary_infos(bin_f)
  File "/usr/local/lib/python3.10/site-packages/libpastis/package.py", line 266, in _read_binary_infos
    mapping = {lief.ELF.ARCH.x86_64: Arch.X86_64,
AttributeError: type object 'ARCH' has no attribute 'x86_64'. Did you mean: 'X86_64'?
Return code: 1
```

Does this enum usage need to be updated?

**Comment by RobinDavid** [comment]
Hello @addisoncrump.
Yes I think you are right as of LIEF 0.15+ enums all seem's to be in capital case: https://lief.re//doc/latest/api/python/elf.html#lief.ELF.ARCH
I doubled check and 0.14 have lower-case ones.

We are going to update that and force using LIEF>=0.15.

Thanks for the finding! _(will close when fixed)_

**Comment by addisoncrump** [comment]
In the meantime, I've pinned the LIEF version for my fuzzbench run. Thanks!

**Comment by cnheitman** [comment]
Hello. I've just pushed a new version of Pastis (`v1.0.13`) with the fix.

Thanks for reporting!
